// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4dcX1SAaKsT4CsqWJEjxusVxlck1x05E',
    appId: '1:673080187992:web:e19885f3865b7e48cd3e2d',
    messagingSenderId: '673080187992',
    projectId: 'health-check-19465',
    authDomain: 'health-check-19465.firebaseapp.com',
    storageBucket: 'health-check-19465.firebasestorage.app',
    measurementId: 'G-QE75D4ZK04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSAD2d9VfiSnp-E87lOHWKbhpA0Ysexgk',
    appId: '1:673080187992:android:c2a4da642cb03977cd3e2d',
    messagingSenderId: '673080187992',
    projectId: 'health-check-19465',
    storageBucket: 'health-check-19465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmqTkmODyd4-YyAedJrLyQop57P_khnk',
    appId: '1:673080187992:ios:22700e30290cf784cd3e2d',
    messagingSenderId: '673080187992',
    projectId: 'health-check-19465',
    storageBucket: 'health-check-19465.firebasestorage.app',
    iosBundleId: 'com.example.healthCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmqTkmODyd4-YyAedJrLyQop57P_khnk',
    appId: '1:673080187992:ios:22700e30290cf784cd3e2d',
    messagingSenderId: '673080187992',
    projectId: 'health-check-19465',
    storageBucket: 'health-check-19465.firebasestorage.app',
    iosBundleId: 'com.example.healthCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4dcX1SAaKsT4CsqWJEjxusVxlck1x05E',
    appId: '1:673080187992:web:85f888557be03b64cd3e2d',
    messagingSenderId: '673080187992',
    projectId: 'health-check-19465',
    authDomain: 'health-check-19465.firebaseapp.com',
    storageBucket: 'health-check-19465.firebasestorage.app',
    measurementId: 'G-E6XSY702E1',
  );
}
